# Generated by Django 3.0.8 on 2020-08-25 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calisthenics',
            old_name='session_id',
            new_name='session_number',
        ),
        migrations.RenameField(
            model_name='cardio',
            old_name='session_id',
            new_name='session_number',
        ),
    ]
